# Generated by Django 6.0.4 on 2026-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('error', 'Error')], max_length=10, null=True)),
                ('profit', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
