# Generated by Django 6.0.4 on 2026-04-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='mode',
            field=models.CharField(default='PRACTICE', max_length=10),
        ),
    ]
